### ISSUE TITLE
Odstranit z repozitáře velká data

### ISSUE THREAD

**Issue by xtompok** [KoksaJanosch/du2_petr_janos#11]
`adresy.geojson` a `kontejnery.geojson` jsou v repozitáři hned na dvou místech a mají přes 1 MB, což je v poměru ke zdrojovému kódu zbytečně obrovské. Zkušební data je samozřejmě možné v repozitáři nechat, ta mají vhodnou velikost.

**Comment by KoksaJanosch** [comment]
nechal jsem pouze data zkušební, které obsahují 8 bodových záznamů
