### ISSUE TITLE
# ? a # ! vypadají zvláštně

### ISSUE THREAD

**Issue by xtompok** [KoksaJanosch/du2_petr_janos#9]
Otazníky a vykřičníky na začátku komentáře bych vypustil, nemají tam podle mne význam a matou, protože často takovýmito sekvencemi začínají nějaké speciální bloky

**Comment by KoksaJanosch** [comment]
Používám extension pro vs code `Better comments`, která obarví komentáře dle prvního znaku (! - červená, ? - modrá atd.), komentáře jsou tak pro mě mnohem více přehlednější.

**Comment by xtompok** [comment]
Pak je to v pořádku a klidně to tam nech.
